[package]
name = "cv-fry"
version = "0.1.0"
edition = "2024"
build = "test/build.rs"

[lib]
path = "test/lib.rs"

[build-dependencies]
cc = "1.2.55"

[[test]]
name = "pc"
path = "test/pc/pc.rs"
[[test]]
name = "alu"
path = "test/alu/alu.rs"

[dev-dependencies]
proptest = "1.10.0"


