[build]
# Sets the default target so you don't need --target in your command
target = "riscv64imac-unknown-none-elf"

[unstable]
# This tells Cargo to compile the core and compiler_builtins 
# crates from source using your project's settings.
build-std = ["core", "compiler_builtins"]

[target.riscv64imac-unknown-none-elf]
# Move your linker script and other flags here
rustflags = [
    "-C", "link-arg=-T../linker.ld",
    "-C", "link-arg=--no-relax",
    "-C", "relocation-model=static",
    "-C", "no-redzone",
    "--cfg", "portable_atomic_unsafe_assume_single_core",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"